export {default as Navbar} from './Navbar/Navbar'
export {default as Footer} from './Footer/Footer'
export {default as Aside} from './Aside/Aside'
export {default as Sidebar} from './Sidebar/Sidebar'
export {default as Slider} from './Slider/Slider'
export {default as Foods} from './Foods/Foods'
export {default as Set} from './Set/Set'
